[workspace]
resolver = "2"

members = [
    "aoc_utils",
    "aoc_utils_tests",
    "d1_trebuchet",
    "d4_scratchcards",
    "d5_fertilizer",
    "d6_wait_boat",
    "d7_camel_cards",
    "d8_haunted_wasteland",
    "d9_mirage_maintenance",
    "d10_pipe_maze"
]
